os: linux
dist: trusty
sudo: false

arch:
   - amd64
   - ppc64le
language: perl

perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

env:
  global:
    - JOBS=3
    - PERL_MM_USE_DEFAULT=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=0
    - NET_SSLEAY=1.88
  matrix:
    - OPENSSL_VERSION=openssl-1.1.1f
    - OPENSSL_VERSION=openssl-1.1.1d
    - OPENSSL_VERSION=libressl-2.9.2
    - OPENSSL_VERSION=libressl-3.0.2
    - OPENSSL_VERSION=openssl-1.1.0l
    - OPENSSL_VERSION=openssl-1.0.2u
    - OPENSSL_VERSION=openssl-1.0.1u
    - OPENSSL_VERSION=openssl-1.0.0s
    - OPENSSL_VERSION=openssl-0.9.8zh

matrix:
  exclude:
  - perl: "5.8"
    env: OPENSSL_VERSION=openssl-1.1.0l
  - perl: "5.8"
    env: OPENSSL_VERSION=openssl-1.1.1d

cache:
  directories:
  - openssl_version_cache
  - net_ssleay_cache

before_install:
  - mkdir -p openssl_version_cache/src
  - mkdir -p openssl_version_cache/build
  - mkdir -p net_ssleay_cache/src
  - mkdir -p net_ssleay_cache/build

install:
  - |
    if [ ! -f openssl_version_cache/src/$OPENSSL_VERSION.tar.gz ]; then
      echo $OPENSSL_VERSION | grep -q libressl
      if [ $? -eq 0 ]; then
        url=https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/$OPENSSL_VERSION.tar.gz
      else
        url=https://www.openssl.org/source/$OPENSSL_VERSION.tar.gz
      fi
      wget -k -P openssl_version_cache/src $url
    fi
  - if [ ! -f net_ssleay_cache/src/$NET_SSLEAY.zip ]; then wget -k -P net_ssleay_cache/src https://github.com/noxxi/p5-net-ssleay/archive/$NET_SSLEAY.zip; fi

before_script:
  - |
    if [ ! -d openssl_version_cache/build/$OPENSSL_VERSION ]; then
      if [ ! -d openssl_version_cache/src/$OPENSSL_VERSION ]; then
        cd openssl_version_cache/src
        tar xzf $OPENSSL_VERSION.tar.gz || exit 1
        cd ../..
      fi
      if [ ! -d openssl_version_cache/src/$OPENSSL_VERSION ]; then
        echo "ERROR Dir openssl_version_cache/src/$OPENSSL_VERSION does not exist" && exit 1
      fi
      cd openssl_version_cache/src/$OPENSSL_VERSION
      echo $OPENSSL_VERSION | grep -q libressl
      if [ $? -eq 0 ]; then
        ./configure --prefix=$PWD/../../build/$OPENSSL_VERSION
        make install > build.log 2>&1 || (cat build.log && exit 1)
      elif [ "$OPENSSL_VERSION" = "openssl-1.0.0s" ] || [ "$OPENSSL_VERSION" = "openssl-0.9.8zh" ]; then
        ./Configure linux-x86_64 --prefix=$PWD/../../build/$OPENSSL_VERSION --openssldir=$PWD/../../build/$OPENSSL_VERSION/ssl shared -Wa,--noexecstack > build.log 2>&1 || (cat build.log && exit 1)
        make > build.log 2>&1 || (cat build.log && exit 1)
        make install_sw > build.log 2>&1 || (cat build.log && exit 1)
        make install_ssldirs > build.log 2>&1 || (cat build.log && exit 1)
      else
        ./Configure linux-x86_64 --prefix=$PWD/../../build/$OPENSSL_VERSION --openssldir=$PWD/../../build/$OPENSSL_VERSION/ssl enable-shared -Wa,--noexecstack > build.log 2>&1 || (cat build.log && exit 1)
        make -j$JOBS > build.log 2>&1 || (cat build.log && exit 1)
        make install_sw > build.log 2>&1 || (cat build.log && exit 1)
        make install_ssldirs > build.log 2>&1 || (cat build.log && exit 1)
      fi
      cd ../../..
    fi
  - |
    DIR=$PWD
    cd net_ssleay_cache/build/
    rm -rf p5-net-ssleay-$NET_SSLEAY
    unzip ../src/$NET_SSLEAY.zip
    cd p5-net-ssleay-$NET_SSLEAY
    OPENSSL_PREFIX=$DIR/openssl_version_cache/build/$OPENSSL_VERSION LD_LIBRARY_PATH=$DIR/openssl_version_cache/build/$OPENSSL_VERSION/lib perl Makefile.PL
    make test
    cd $DIR

script:
  - |
    export PERL5OPT=-Mblib=$DIR/net_ssleay_cache/build/p5-net-ssleay-$NET_SSLEAY/blib
    perl Makefile.PL
    make
    make TEST_VERBOSE=1 test
